name: MyPlaceholder
version: '${project.version}'
main: dev.risas.myplaceholder.MyPlaceholder
api-version: '1.20'
author: Risas, nutellim
description: MyPlaceholder
depend: [PlaceholderAPI]
softdepend: [Vault]
commands:
  myplaceholder:
    description: MyPlaceholder Command
    permission: myplaceholder.command.myplaceholder
    aliases: [mp]